### ISSUE TITLE
Problem with Django 1.7 migrations?

### ISSUE THREAD

**Issue by jannon** [djangonauts/django-hstore#103] opened 2015-04-01 04:54 UTC
I just ran my first migration on a model that has an hstore field in it.  I had changed the default of a datetime field within the hstore field (because of https://github.com/tomchristie/django-rest-framework/issues/2687) and the migration blew up with:
```
ValueError: Cannot alter field batches.Collection.end_date into app.MyModel.end_date - they do not properly define db_type (are you using PostGIS 1.5 or badly-written custom fields?)
```
So I took a look at what the migration was doing:
```python
migrations.AlterField(
            model_name='mymodel',
            name='end_date',
            field=django_hstore.virtual.VirtualField(default=datetime.date(2015, 1, 1)),
        )
```
It seems like the django_hstore.virtual.VirtualField fields shouldn't be included in the migration.  I wanted to check and see if others had this issue or if I was just missing something before I looked in to how we might avoid this (other than manually editing the migration every time)

**Comment by nemesisdesign** [comment] 2015-04-01 07:57
Oh no again.
I tried reporting this problem last year:
https://code.djangoproject.com/ticket/23159
I also sent a pull request: https://github.com/django/django/pull/3013/files
But I was adviced to just set `db_type` as `None` in the virtual fields by @andrewgodwin and the issue was set as won't fix.
It some more tricks I was able to make the basic cases just work fine, but the solutions I found might not work in all cases, like yours.

So, I don't really know how to proceed. Apart from just deleting part of the migration manually, which obviously sucks but will work if in a hurry, we could do two things:

* insist to reopen the issue and find a way to tell the django migration framework to ignore virtual fields
* implement a hack of the hack that will work on some more cases until another bug comes up

Federico

**Comment by jannon** [comment] 2015-04-02 00:52
Bah! Okay, yeah I doubt that we'd get them to reopen the issue, especially given Django1.8's new HStoreField.  Until I get a chance to see how 1.8 works, or until the DRF bug gets fixed, I think I'll just manually edit the migrations

**Comment by nemesisdesign** [comment] 2015-04-02 12:16
Ok @jannon.

**Comment by timgraham** [comment] 2015-04-02 12:50
Can you paste the model field before and after?

**Comment by nemesisdesign** [comment] 2015-04-10 08:31
@jannon could you answer to @timgraham's question please?

**Comment by jannon** [comment] 2015-04-10 11:34
Before:
```python
class MyModel(models.Model):
    hstore_field = hstore.DictionaryField(schema=[
        {
            'name': 'end_date',
            'class': 'DateField',
            'kwargs': {'null': True, 'blank': True}
        }
    ], null=True, blank=True)
```

After:
```python
class MyModel(models.Model):
    hstore_field = hstore.DictionaryField(schema=[
        {
            'name': 'end_date',
            'class': 'DateField',
            'kwargs': {'null': True, 'blank': True, 'default': date(2015, 1, 1)}
        }
    ], null=True, blank=True)
```

**Comment by timgraham** [comment] 2015-04-10 13:27
I think the migration that's generated is correct, but Django doesn't seem to have good support for ignoring virtual fields in the schema editor. You might be able to workaround it by adding a `rel` attribute to `django_hstore.virtual.VirtualField` with the appropriate sub-attributes so that you reach the [no-op branch](https://github.com/django/django/blob/190afb86187e42c449afe626cff31f65b4781aa2/django/db/backends/base/schema.py#L470-L475) in the schema editor. 

This might be properly fixed if Django gains support for composite fields in 1.9, but it seems like a ticket is justified (a separate one from what was originally reported).

**Comment by nemesisdesign** [comment] 2015-04-10 14:27
thx for the info @timgraham, is there any link where we can find more information? A mailing list thread, a ticket, or anything else?

**Comment by timgraham** [comment] 2015-04-10 14:33
More information about what? Composite field DEP is here if that's what you meant: https://github.com/django/deps/pull/12

**Comment by nemesisdesign** [comment] 2015-04-10 14:37
Exactly, thank you.

**Comment by nemesisdesign** [comment] 2015-04-19 11:01
@timgraham & @jannon I pushed a possible fix for the ValueError in e3ff9bf, the problem is I don't have a clue of how to make a failing test case ... :-1: any hints?

**Comment by nemesisdesign** [comment] 2015-04-19 13:25
After some manual testing it turned out the code e3ff9bf was not effective.

Thanks to @apollo13's help I come up with 618f1ff which correctly eliminates the ValueError, the problem is I still can't figure out how to test this automatically.

**Comment by timgraham** [comment] 2015-04-20 12:21
You might take inspiration from Django's test suite: https://github.com/django/django/blob/master/tests/schema/tests.py

**Comment by nemesisdesign** [comment] 2015-04-22 07:56
It should be fixed.

Thanks to everyone who helped out: @jannon for reporting, @timgraham and @apollo13 for helping me with suggestions.

I opened a new thread on django-developers here: https://groups.google.com/forum/#!topic/django-developers/_FmJRK3sJGs

I received another suggestion by @MarkusH which I'll try out before closing this issue.

**Comment by jannon** [comment] 2015-04-22 16:05
Federico,
This works great! 
It'll be nice if the the ```virtual=True``` suggestion will even help clean things up a bit

**Comment by nemesisdesign** [comment] 2015-04-23 17:36
I mark this closed for the moment, but I'll keep following the mailing list for suggestions.

**Closed by nemesisdesign** 2015-04-23 17:36 UTC
Labels: bug
